spring:
  application:
    name: spring-boot-crud-mvc-perf-test
  main:
    web-application-type: reactive
  profiles:
    active: local
management:
  endpoints:
    web:
      exposure:
        include: health,info
server:
  port: 8080
  error:
    include-binding-errors: always

---
spring:
  config:
    activate:
      on-profile: local
  r2dbc:
    username: dummy_user
    password: Pa88w0rd
    schema-name: product_db
    url: r2dbc:postgresql://localhost:5432/${spring.r2dbc.schema-name}
  liquibase:
    enabled: true
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
    url: jdbc:postgresql://localhost:5432/${spring.r2dbc.schema-name}
    change-log: classpath:liquibase/changelog.xml

---
spring:
  config:
    activate:
      on-profile: remote
  r2dbc:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    schema-name: product_db
    url: r2dbc:postgresql://${DB_HOST}:${DB_PORT}/${spring.r2dbc.schema-name}
  liquibase:
    enabled: true
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${spring.r2dbc.schema-name}
    change-log: classpath:liquibase/changelog.xml

